In [11]:
import pandas as pd
import os

In [15]:
def individual_building_csv(building):
    '''
    Extracts and exports data related to professors, rooms, emails,
    floors, and buildings for a specified building.

    Parameters
    ----------
    building : str
        gets the name of the building

    Returns
    -------
    csv
        a csv per building on the dataset 
    '''
    building_info = []
    for element in range(len(data)):
        if building in data["facil_name"][element]:
            cornell_building = building
            floor = data["ROOM"][element][0]
            room = data["ROOM"][element]
            people = data["Primary"][element]
            email = ""

            if "(" in people:
                parenthesis = people.index("(")
                email = people[parenthesis+1:-1] + "@cornell.edu"
                people = people[:parenthesis]

            building_info.append({"Building": cornell_building, "Floor": floor,
                                  "Room": room, "People": people, "Email": email})

    building_df = pd.DataFrame(building_info)
    name_of_building_concat = building + ".csv"
    # building_df.to_csv(name_of_building_concat, index = True)


def get_professor_and_email(building):
    '''
    Extracts and exports data related to professors and their emails.

    Parameters
    ----------
    building : str
        gets the name of the building

    Returns
    -------
    csv
        a csv per building on the dataset that has their information 
        without the floor, room, and building. 
    '''

    csv_location = './All_building_information' + '/' + building + '.csv'
    csv_reader = pd.read_csv(csv_location, delimiter=',')
    professors_emails = csv_reader[['People', 'Email']]

    professors_emails = professors_emails.drop_duplicates()


    output_folder = './Professor_information'
    output_path = os.path.join(output_folder, building + '.csv')

    # professors_emails.to_csv(output_path, index=False)

data = pd.read_csv('All Rooms of Interest_data_2_14_2024.csv')

all_buildings = []
data_buildings = set(data["facil_name"])

for building in data_buildings:
    all_buildings.append(building)

for building in all_buildings:
    individual_building_csv(building)
    get_professor_and_email(building)

Organization Desc
Dept Description
facil_name
Building_coord
ROOM
room_type
Day of UPD_DATE
Primary

In [14]:
data

,Organization Desc,Dept Description,facil_name,Building_coord,ROOM,room_type,Day of UPD_DATE,Primary
0,Agriculture and Life Sciences,CALS Animal Science,Bondareff Raptor Facility(1103),NaN,101,ANIMAL QUARTERS (570),23-Nov-15,John Parks (jep5)
1,Agriculture and Life Sciences,CALS Animal Science,Bondareff Raptor Facility(1103),NaN,102,ANIMAL QUARTERS (570),23-Nov-15,John Parks (jep5)
2,Agriculture and Life Sciences,CALS Animal Science,Bondareff Raptor Facility(1103),NaN,103,ANIMAL QUARTERS (570),23-Nov-15,John Parks (jep5)
3,Agriculture and Life Sciences,CALS Animal Science,Bondareff Raptor Facility(1103),NaN,104,ANIMAL QUARTERS (570),23-Nov-15,John Parks (jep5)
4,Agriculture and Life Sciences,CALS Animal Science,Bondareff Raptor Facility(1103),NaN,106,ANIMAL QUARTERS (570),23-Nov-15,John Parks (jep5)
...,...,...,...,...,...,...,...,...
3739,Veterinary Medicine,Quality Milk Production Service,Mastitis Lb Canton Newell VTC(1409),NaN,100E,NON-CLASS LABORATORY SERVICE (255),24-Apr-23,Paul Virkler (pdv3)
3740,Veterinary Medicine,Veterinary Curriculum,Basic Science Building(1150D),Peggy Emerson (PLE7),S2065,INDIVIDUAL STUDY LABORATORY (230),1-Feb-24,Paul Maza (psm26)
3741,Veterinary Medicine,Veterinary Curriculum,Basic Science Building(1150D),Peggy Emerson (PLE7),S2067,INDIVIDUAL STUDY LABORATORY (230),9-Aug-22,Paul Maza (psm26)
3742,Veterinary Medicine,Veterinary Curriculum,Equine Park Brood Mare Barn(1141H),Andrew Brooks (AHB35),120,ANIMAL QUARTERS SERVICE (575),1-Nov-23,Jessica Crumb (jg884)
3743,Veterinary Medicine,Veterinary Curriculum,Equine Park Farrier Shop(1141J),Andrew Brooks (AHB35),101,ANIMAL QUARTERS SERVICE (575),1-Nov-23,Jessica Crumb (jg884)